### ISSUE TITLE
-noixemul option ignored?

### ISSUE THREAD

**Issue by anchor76** [bebbo/amigaos-cross-toolchain#10]
hello,

i tried to compile a C project to OS3.x. i use **-noixemul** option, but i got these linker errors below:
(this project is compiles fine with gcc 2.95.3) why is **libnix.a** here?
info: if i ask the compiler version, i see this: _Configured with: ... --with-headers=/cygdrive/c/!/_development/amigaos-cross-toolchain/.build-m68k/sources/ixemul-48.2/include_

/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x13c): In function `__floatsidf':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:174: multiple definition of `__floatsidf'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__floatsidf.o)(.text+0x0):__floatsidf.o: first defined here
/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x2b0): In function `__truncdfsf2':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:275: multiple definition of `__truncdfsf2'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__truncdfsf2.o)(.text+0x0):__truncdfsf2.o: first defined here
/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x218): In function `__floatsisf':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:228: multiple definition of `__floatsisf'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__floatsisf.o)(.text+0x0):__floatsisf.o: first defined here
/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x234): In function `__extendsfdf2':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:236: multiple definition of `__extendsfdf2'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__extendsfdf2.o)(.text+0x0):__extendsfdf2.o: first defined here
/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x404): In function `__fixdfsi':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:343: multiple definition of `__fixdfsi'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__fixdfsi.o)(.text+0x0):__fixdfsi.o: first defined here
/opt/m68k-amigaos-6/lib/gcc/m68k-amigaos/6.3.1a/libgcc.a(fpgnulib.o)(.text+0x49c): In function `__fixsfsi':
/cygdrive/c/!/_development/amigaos-cross-toolchain/submodules/gcc-6/libgcc/config/m68k/fpgnulib.c:375: multiple definition of `__fixsfsi'
/opt/m68k-amigaos-6/m68k-amigaos/libnix/lib/libm020/libnix/libnix.a(__fixsfsi.o)(.text+0x0):__fixsfsi.o: first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile.os3:38: all_os3] Error 1

**Comment by bebbo** [comment]
The -noixemul option is working.

Your problem arises because the semantics of inline has changed. Here is a good explanation for issues with[static/extern inline](http://stackoverflow.com/questions/216510/extern-inline).

The current workaround is the linker option **--allow-multiple-definition** which can be passed from gcc via **-Xlinker --allow-multiple-definition**.

**Comment by anchor76** [comment]
thanks!!! ;)
