### ISSUE TITLE
-noixemul -m68020-60 -m68881 -> multiple definition of sin, cos, tan etc

### ISSUE THREAD

**Issue by githubaf** [bebbo/amigaos-cross-toolchain#56]
Used version:
commit 1de381e58c72da9c592aebc9a406422165b22fcd
Author: fautomat <automat@franke.ms>
Date:   Tue Dec 19 19:03:15 2017 +0100
    update submodule gcc-6

When I compile and link with -noixemul -m68020-60 -m68881 I get duplicated symbols for math functions like sin, con, tan...

The same commandline works with gcc2.95.3 from cahirwpz/amigaos-cross-toolchain

[m68020-60-m68881_linkerror.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1582587/m68020-60-m68881_linkerror.zip)

**Comment by bebbo** [comment]
should be fixed in b9a4782d9d6fecf1f5459ac84d270c5bfefe5754

please test
